const translations={fr:{},en:{},es:{},it:{},pt:{},de:{}};function setLang(lang){localStorage.setItem('atf_lang',lang);document.documentElement.lang=lang;document.querySelector('.lang').value=lang}function initLang(){const l=localStorage.getItem('atf_lang')||'fr';const s=document.querySelector('.lang');if(s){s.value=l;s.addEventListener('change',e=>setLang(e.target.value))}}document.addEventListener('DOMContentLoaded',initLang);
/* V5.1 social network prototype */
function getConnections(){try{return JSON.parse(localStorage.getItem('atf_connections')||'[]')}catch(e){return[]}}
function saveConnections(a){localStorage.setItem('atf_connections',JSON.stringify(a))}
function renderConnections(){const box=document.getElementById('connections');if(!box)return;const a=getConnections();box.innerHTML=a.length?a.map(n=>'<div class="connection"><span>🤝 '+n+'</span><button class="btn secondary" onclick="openChat('+JSON.stringify(n)+')">Message</button></div>').join(''):'<p class="muted">Aucune connexion pour le moment.</p>'}
function connectUser(name){const a=getConnections();if(!a.includes(name)){a.push(name);saveConnections(a);renderConnections();alert(name+' a été ajouté à votre réseau.')}else alert('Vous êtes déjà connecté à '+name+'.')}
function openChat(name){const c=document.getElementById('chatContact'),w=document.getElementById('chatWindow');if(c)c.textContent='Discussion avec '+name;if(w)w.innerHTML='<div class="bubble">Bonjour ! Bienvenue dans la messagerie ATF.</div>';const el=document.getElementById('chat');if(el)el.scrollIntoView({behavior:'smooth',block:'center'});localStorage.setItem('atf_chat_contact',name)}
function sendChat(){const i=document.getElementById('chatInput'),w=document.getElementById('chatWindow');if(!i||!w||!i.value.trim())return;const d=document.createElement('div');d.className='bubble me';d.textContent=i.value.trim();w.appendChild(d);i.value='';w.scrollTop=w.scrollHeight}
function filterNetwork(){const q=(document.getElementById('networkSearch')?.value||'').toLowerCase();document.querySelectorAll('[data-search]').forEach(e=>e.style.display=(!q||e.dataset.search.toLowerCase().includes(q))?'block':'none')}
document.addEventListener('DOMContentLoaded',()=>{renderConnections()});
